version: "3.8"

services:
  backend:
    build: ./panda_api
    container_name: panda_backend
    volumes:
      - ./panda_api:/app
    ports:
      - "8000:8000"
    env_file:
      - ./panda_api/.env
    depends_on:
      - db

  frontend:
    build: ./panda-ui
    container_name: panda_frontend
    volumes:
      - ./panda-ui:/app
    ports:
      - "3000:3000"
    env_file:
      - ./panda-ui/.env.local
    depends_on:
      - backend

  db:
    image: postgres:14
    container_name: panda_db
    environment:
      POSTGRES_DB: panda
      POSTGRES_USER: panda
      POSTGRES_PASSWORD: panda
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
